-- CatFacts.lua
-- Fact list for the "/mia cat" slash command (see UI_Main.lua).
-- Kept as plain data here (not in cat.md, which is not part of the addon)
-- so new facts can be appended by hand without touching any logic.

local ADDON_NAME, ns = ...

ns.CatFacts = {
  "Although cats are often described as solitary animals, many form close social bonds with other cats, provided those other cats have acceptable opinions.",
  "Domestic cats are capable of learning hundreds of different behaviors through observation and repetition, but they generally avoid demonstrating this because it creates expectations.",
  "Cats blink slowly to communicate trust and affection. Humans call this \"trying not to cry.\"",
  "The average adult cat has around 230 bones, 517 muscles, and exactly zero interest in proving any of the things you just told your friends it can do.",
  "A cat's vision is optimized for detecting movement over detail, explaining why they can spot a moth across the house but remain completely unaware of the medication hidden in a piece of cheese.",
  "The average cat spends nearly 15% of its waking life looking out windows, gathering intelligence that it refuses to share with the rest of us.",
  "Cats have an instinctive righting reflex that begins developing at around three weeks of age, which is still several decades earlier than most people learn to admit they were wrong.",
  "The average domestic cat weighs between 8 and 10 pounds, yet can somehow increase to approximately 400 pounds whenever it's time to put it in a carrier.",
  "Cats have extraordinary spatial awareness, allowing them to leap onto narrow ledges with incredible precision before immediately forgetting why they went there.",
  "Cats can detect ultraviolet light that is invisible to humans, meaning they know things about your carpet that you never will.",
  "The world's oldest known cat reached 38 years of age, a milestone achieved through excellent genetics and an unwavering commitment to making every problem somebody else's.",
  "Domestic cats can accelerate from 0 to 30 mph in just a few seconds, almost always in response to a sound they personally created.",
  "A cat's pupils can contract into extremely narrow slits under bright light, giving them exceptional visual control and an unsettling ability to look profoundly unimpressed.",
  "Researchers found that cats prefer elevated resting places because they offer a wider field of view, greater security, and an improved angle from which to judge everyone below.",
  "Although cats have relatively small brains, the density of neurons within their cerebral cortex is remarkably complex, allowing them to execute plans that can only be described as personal.",
  "The average cat performs thousands of tiny balance corrections every single day without conscious thought, which is more emotional regulation than most adults manage in a lifetime.",
  "A cat's purr typically falls between 25 and 150 hertz, a frequency range associated with healing bone and soft tissue according to some researchers, and repairing absolutely nothing else.",
  "Although cats are obligate carnivores, they remain inexplicably committed to eating ribbon, cardboard, electrical cables, and roughly four square feet of your favorite houseplant.",
  "Cats possess a highly developed sense of proprioception, allowing them to know exactly where every part of their body is at all times, including the part currently occupying your keyboard.",
  "Some researchers believe domestic cats have learned to interpret dozens of human emotional cues through thousands of years of coexistence. They have published nothing because it's funnier this way.",
  "Domestic cats share roughly 95% of their DNA with tigers, explaining why both species occasionally stare into empty corners until everyone else becomes uncomfortable.",
  "A cat's nose contains over 200 million scent receptors, making its sense of smell roughly fourteen times stronger than yours and therefore fully capable of detecting the emotional residue of your life choices.",
  "Feline reaction times average around 20 milliseconds, allowing them to avoid danger with astonishing precision while still occasionally falling off furniture they personally climbed onto.",
  "The average house cat spends roughly five hours every day grooming itself, which is still less time than it spends pretending it wasn't just licking plastic for twenty minutes.",
  "Researchers estimate there are more than 600 million domestic cats alive today, though nobody has managed to perform an accurate census because the cats refused to participate in something so demeaning.",
  "Most cats have 18 toes, though some naturally develop extra toes in a condition known as polydactyly, allowing them to ignore you with even greater dexterity.",
  "A cat's pupils can expand until they occupy almost the entire visible eye, a useful adaptation for hunting at night and for convincing you they've just witnessed something standing behind you.",
  "A healthy domestic cat's heart beats between 140 and 220 times per minute, increasing dramatically whenever absolutely nothing is happening.",
  "Behavioral studies indicate that cats prefer predictable environments with stable routines, although they reserve the right to become deeply offended by those same routines without notice.",
  "A cat's whiskers can detect air currents so subtle they're almost impossible to measure, making them one of the few known instruments capable of confirming that something is, in fact, weird in here.",
  "The average domestic cat sleeps between 12 and 16 hours every day, leaving a surprisingly small amount of time to be responsible for everything else.",
  "Although cats rarely vocalize to one another in adulthood, they readily develop entirely new sounds when they discover they can confuse a human with them.",
  "Behavioral studies suggest that cats can distinguish between intentional and accidental actions performed by humans, but remain committed to misinterpreting both.",
  "Every hair on a cat's body grows in a specific direction that helps regulate temperature and moisture, except the one currently floating directly toward your coffee.",
  "Cats like beetles.",
  "Cats possess a Jacobson’s organ in their mouth to analyze airborne pheromones, which is why they make an open-mouthed expression called the flehmen response, during which they actively index your sins.",
  "They remember.",
  "Cats walk like camels and giraffes in a \"pacing\" gait: both right legs move together, then both left. This smooth, swaying motion allows them to glide across the room like a small, carnivorous ottoman.",
  "A domestic cat’s skeleton contains no functional collarbone, which allows its chest to collapse slightly and squeeze through any space wider than its head, or, if the lighting is bad enough, a narrow crack in the conversation.",
  "Cats do not possess sweet taste receptors, making them completely indifferent to sugar, fruit, and your heartfelt attempts to reason with them.",
  "A cat's tail acts as a dynamic counterbalance during precise jumps, sharp turns, and brief moments where they pretend to lose interest in a bug.",
  "Cats lack the salivary enzymes to digest starches in their mouth, requiring all complex carbohydrates to be processed lower in the digestive tract or left on the rug.",
  "Did you know, cats spend nearly 50% of their waking hours grooming themselves to regulate body temperature, remove loose fur, and completely erase any physical proof that you held them like a little baby?",
  "A cat’s outer ear is controlled by 14 million independent muscles, allowing each pinna to rotate 360 degrees at rotational speeds exceeding 600 RPM.",
  "Domestic cat claws extend via digital flexor tendons in 0.01 seconds, deploying over 500 sharp keratin sheaths per paw.",
  "A cat’s paw pads contain sub-epidermal mechanoreceptors capable of detecting seismic micro-vibrations as small as 0.04 Hz from up to 80 meters away.",
  "Feline whiskers feature vibrissal proprioceptors with 180 nerve endings per millimeter, allowing them to measure spatial gaps down to 0.3 millimeters.",
  "Cats possess a thoracic elastic suspension system instead of a rigid collarbone, allowing chest compression down to 38% of their natural standing width.",
  "A cat's tongue contains 470 keratinized lingual spicules shaped like micro-scoops, which draw 0.12 milliliters of fluid upward per lap at 4.1 laps per second.",
  "The dorsal-caudal reflex arc in a cat's tail executes 14 subtle micro-adjustments per second, maintaining dynamic center-of-mass balance during leaps.",
  "A cat’s bite force is amplified by temporomandibular leverage, generating 140 pounds of pressure per square inch through their carnassial teeth.",
  "The supra-orbital vibrissal array above a cat's eyes triggers a corneal blink reflex in 18 milliseconds when objects approach within 2.4 centimeters.",
  "Female tortoiseshell cats can accurately distinguish between genuine leather and vinyl.",
  "Siamese cats possess vocal cords capable of producing a pitch almost identical to a quiet microwave beep.",
  "Female cats exhibit a strong neurological preference for using their right paw when manipulating small objects, particularly when attempting to open their mail.",
  "Domesticated cats have a reduced digestive capacity for plant sugars, which causes them to smell fresh citrus.",
  "Older tabby cats will drink fresh water from a bowl, but show a measurable preference for water that was poured when you were on your last limb and ready to call it quits.",
}
